### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by murphy214** [mapbox/osmpbf-tutorial#1]
This tutorial is awesome for people wanting to work with osmpbf files I was recently hacking on this stuff and the osmpbf spec is quite verbose. Anyway I was wondering if I could ask a few questions that maybe you would know: 

Firstly, can densenodes only make up relations and ways or can regular nodes as well? 

The second questions relates to how the data is encoded. Are end user features encoded in a sequential manner in regards to their fileblock locations. For example I noticed in my cursory research I noticed that densenodes basically encoded as their feature counterparts in order (which is to be expected for zigzag encoding), but relations that were next to each (in a relation fileblock) other did this as well. 

Can I expect densenode fileblocks to roughly correspond with a certain relation block farther down in pbf file. 

Or is this not a relationship that can be relied on? Because if that were the case you could basically walk over each object file block relating back to a polygon, its relations, and its nodes at the same time which would be really cool. Sorry if this question doesn't make any sense. I accidently opened this issue and I'm making the most it. Closing lol.

Again awesome tutorial if I had a month ago it would have saved me a few hours!

**Comment by Yuffster** [comment]
> Firstly, can densenodes only make up relations and ways or can regular nodes as well?

Regular nodes can as well!  Regular Nodes and DenseNodes are essentially the same, except the filesize is much smaller for Dense ones.

I'm currently trying to find a regular Node in the wild to get an example dump; if you happen to come across some let me know the file and block number and I can go through it in the tutorial.

> Can I expect densenode fileblocks to roughly correspond with a certain relation block farther down in pbf file?

I personally wouldn't rely on any correspondences that aren't [explicitly specified](https://wiki.openstreetmap.org/wiki/PBF_Format), just because you never know if the upstream tools doing conversion have made any minor changes.

Of course, this doesn't stop you from creating and relying on your own expanded specification if you're doing your own dumps.

> Are end user features encoded in a sequential manner in regards to their fileblock locations. 

The delta encoding scheme implies there's definitely an incentive to dump these things in *some* sequential order, but of course the question is *which* sequence.  If you take a look at some of the DenseNode dumps, though, you'll find a lot of `x00` groups which are an indication that each of the nodes specified by that group are part of the same insert operation.

> Or is this not a relationship that can be relied on? Because if that were the case you could basically walk over each object file block relating back to a polygon, its relations, and its nodes at the same time which would be really cool.

Yes.  What a world that would be; with a slightly expanded specification and proper boundary encoding for each block...  

I've been using [HTTP Range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) requests in my [own work](https://github.com/mapbox/planetstream) to skip around a bit; but I haven't found any reliable pattern to the data.  See the above notes on delta-encoding of insert batches, though; people tend to do a set of polygons in one update operation through their editor.  

One problem of course is that these entities like ways can overlap on boundaries, which would cause a duplicate entry error if you're trying to get your dump into Postgis.  Could be solved by patching the tools to add an [ON CONFLICT DO NOTHING](https://www.postgresql.org/docs/9.5/static/sql-insert.html#SQL-ON-CONFLICT) clause to the INSERT statements.

If you're doing your own dumps, though, you could always create an expanded specification for them.

> Sorry if this question doesn't make any sense. I accidently opened this issue and I'm making the most it. Closing lol.

No worries; make as many issues as you like!  The whole point of the tutorial is to answer your questions, so any questions you do have are super valuable feature requests.
